// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Membership.Entities.QuocDT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Membership.Repositories.QuocDT.DBContext;

public partial class CarWashManagementSystemContext : DbContext
{
    public CarWashManagementSystemContext(DbContextOptions<CarWashManagementSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CustomerMembershipsQuocDt> CustomerMembershipsQuocDts { get; set; }

    public virtual DbSet<MembershipTiersQuocDt> MembershipTiersQuocDts { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CustomerMembershipsQuocDt>(entity =>
        {
            entity.HasKey(e => e.MembershipIdquocDt).HasName("PK__Customer__C45A5B2F9C1B5AD1");

            entity.ToTable("CustomerMembershipsQuocDT");

            entity.Property(e => e.MembershipIdquocDt)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("MembershipIDQuocDT");
            entity.Property(e => e.CurrentPointsBalance).HasDefaultValue(0);
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsAutoRenewalActive).HasDefaultValue(true);
            entity.Property(e => e.JoinDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LastReviewDate).HasColumnType("datetime");
            entity.Property(e => e.MonthlySpendToDate)
                .HasDefaultValue(0.00m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TierId).HasColumnName("TierID");
            entity.Property(e => e.TotalLifetimeVisits).HasDefaultValue(0);

            entity.HasOne(d => d.Tier).WithMany(p => p.CustomerMembershipsQuocDts)
                .HasForeignKey(d => d.TierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerMemberships_Tiers");
        });

        modelBuilder.Entity<MembershipTiersQuocDt>(entity =>
        {
            entity.HasKey(e => e.TierIdquocDt).HasName("PK__Membersh__F320052594CDA51F");

            entity.ToTable("MembershipTiersQuocDT");

            entity.Property(e => e.TierIdquocDt).HasColumnName("TierIDQuocDT");
            entity.Property(e => e.RequiredSpend).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TierName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}