<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\customer.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Membership.Entities.QuocDT\Membership.Entities.QuocDT.csproj" />
    <ProjectReference Include="..\Membership.Repositories.QuocDT\Membership.Repositories.QuocDT.csproj" />
    <ProjectReference Include="..\Membership.Services.QuocDT\Membership.Services.QuocDT.csproj" />
  </ItemGroup>

</Project>
