// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Membership.Entities.QuocDT.Models;

public partial class CustomerMembershipsQuocDt
{
    public Guid MembershipIdquocDt { get; set; }

    public string CustomerName { get; set; }

    public int TierId { get; set; }

    public DateTime? JoinDate { get; set; }

    public bool? IsAutoRenewalActive { get; set; }

    public int? CurrentPointsBalance { get; set; }

    public DateTime? LastReviewDate { get; set; }

    public decimal? MonthlySpendToDate { get; set; }

    public string MembershipNotes { get; set; }

    public DateOnly? TierExpiryDate { get; set; }

    public int? TotalLifetimeVisits { get; set; }

    public virtual MembershipTiersQuocDt Tier { get; set; }
}