// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Membership.Entities.QuocDT.Models;

public partial class MembershipTiersQuocDt
{
    public int TierIdquocDt { get; set; }

    public string TierName { get; set; }

    public decimal? RequiredSpend { get; set; }

    public double? PointsMultiplier { get; set; }

    public virtual ICollection<CustomerMembershipsQuocDt> CustomerMembershipsQuocDts { get; set; } = new List<CustomerMembershipsQuocDt>();
}