// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Membership.SoapService.QuocDT.SoapModels;

[DataContract]
public partial class CustomerMembershipsQuocDt
{
    [Key]
    [DataMember]
    public Guid MembershipIdquocDt { get; set; }
    [DataMember]
    public string CustomerName { get; set; }
    [DataMember]
    public int TierId { get; set; }
    [DataMember]
    public DateTime? JoinDate { get; set; }

    [DataMember]
    public bool? IsAutoRenewalActive { get; set; }

    [DataMember]
    public int? CurrentPointsBalance { get; set; }
    [DataMember]
    public DateTime? LastReviewDate { get; set; }
    
    [DataMember]
    public decimal? MonthlySpendToDate { get; set; }
    [DataMember]
    public string MembershipNotes { get; set; }
    [DataMember]
    public DateOnly? TierExpiryDate { get; set; }
    [DataMember]
    public int? TotalLifetimeVisits { get; set; }
    
    //public virtual MembershipTiersQuocDt Tier { get; set; }
}