// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Membership.SoapService.QuocDT.SoapModels;

[DataContract]
public partial class MembershipTiersQuocDt
{
    [DataMember]
    public int TierIdquocDt { get; set; }

    [DataMember]
    public string TierName { get; set; }

    [DataMember]
    public decimal? RequiredSpend { get; set; }
    [DataMember]
    public double? PointsMultiplier { get; set; }
    //[DataMember]
    //[System.Text.Json.Serialization.JsonIgnore]
    //public virtual ICollection<CustomerMembershipsQuocDt> CustomerMembershipsQuocDts { get; set; } = new List<CustomerMembershipsQuocDt>();
}